title: Jonathan Juursema
description: My personal homepage

baseurl: null
color-scheme: "#007DFF"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

exclude:
  - .sass-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "default"