name: Deploy Website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-rtx:
    name: Deploy website and resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Test
        run: |
          bundle exec jekyll build
          bundle exec htmlproofer ./_site --disable-external

      - name: Deploy static website to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: jonathanj
          AWS_ACCESS_KEY_ID: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: _site
